import type {Metadata} from 'next';
import {Inter} from 'next/font/google';
import './globals.scss';
import {RelayProvider} from '@lib/relay/provider';
import {ReactNode} from 'react';
import {clsx} from 'clsx';

const inter = Inter({subsets: ['latin']});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({children}: {children: ReactNode}) {
  return (
    <html lang="en">
      <body className={clsx(inter.className, 'container mx-auto bg-slate-100')}>
        <RelayProvider>{children}</RelayProvider>
      </body>
    </html>
  );
}
